# Generated by Django 5.2.17 on 2026-08-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('secteur', models.CharField(max_length=200)),
                ('adresse', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('responsable', models.CharField(max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
