# Generated by Django 5.2.17 on 2026-08-14 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_CREATED', 'Utilisateur créé'), ('USER_UPDATED', 'Utilisateur modifié'), ('USER_DELETED', 'Utilisateur supprimé'), ('COMPANY_CREATED', 'Entreprise créée'), ('COMPANY_UPDATED', 'Entreprise modifiée'), ('STAGE_CREATED', 'Offre de stage créée'), ('STAGE_UPDATED', 'Offre de stage modifiée'), ('STAGE_CLOSED', 'Offre de stage fermée'), ('APPLICATION_CREATED', 'Candidature déposée'), ('APPLICATION_ACCEPTED', 'Candidature acceptée'), ('APPLICATION_REFUSED', 'Candidature refusée'), ('SUPERVISION_CREATED', 'Encadrement créé'), ('JOURNAL_CREATED', 'Journal de stage créé'), ('REPORT_CREATED', 'Rapport déposé'), ('REPORT_VALIDATED', 'Rapport validé'), ('REPORT_REFUSED', 'Rapport refusé'), ('EVALUATION_CREATED', 'Évaluation créée')], max_length=50)),
                ('description', models.TextField()),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_CREATED', 'Utilisateur créé'), ('USER_UPDATED', 'Utilisateur modifié'), ('USER_DELETED', 'Utilisateur supprimé'), ('COMPANY_CREATED', 'Entreprise créée'), ('COMPANY_UPDATED', 'Entreprise modifiée'), ('STAGE_CREATED', 'Offre de stage créée'), ('STAGE_UPDATED', 'Offre de stage modifiée'), ('STAGE_CLOSED', 'Offre de stage fermée'), ('APPLICATION_CREATED', 'Candidature déposée'), ('APPLICATION_ACCEPTED', 'Candidature acceptée'), ('APPLICATION_REFUSED', 'Candidature refusée'), ('SUPERVISION_CREATED', 'Encadrement créé'), ('JOURNAL_CREATED', 'Journal de stage créé'), ('REPORT_CREATED', 'Rapport déposé'), ('REPORT_VALIDATED', 'Rapport validé'), ('REPORT_REFUSED', 'Rapport refusé'), ('EVALUATION_CREATED', 'Évaluation créée')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
