"""
Django settings for config project.

Generated by 'django-admin startproject'
"""

from pathlib import Path
from datetime import timedelta
import os
import dj_database_url


# =========================================================
# CHEMIN PRINCIPAL DU PROJET
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# =========================================================
# SECURITY & PROXY (PRODUCTION)
# =========================================================

SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-d@tv+y*y0a3&cuzw--r-2v(knnrwwqf5jww#p1$wkn_sry5j91')

# Désactivé automatiquement sur Render (Production), activé en local
DEBUG = 'RENDER' not in os.environ

ALLOWED_HOSTS = [
    'gestion-stage-api-r2ts.onrender.com',
    'localhost',
    '127.0.0.1',
]

# Si Render injecte un nom d'hôte externe
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Domaines autorisés pour la protection CSRF (Indispensable pour l'admin Django en HTTPS)
CSRF_TRUSTED_ORIGINS = [
    'https://gestion-stage-api-r2ts.onrender.com',
    'https://*.onrender.com',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')

# Reconnaissance du protocole HTTPS et de l'hôte derrière le proxy inverse de Render
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True


# =========================================================
# APPLICATIONS INSTALLÉES
# =========================================================

INSTALLED_APPS = [

    # -----------------------------------------------------
    # Applications Django
    # -----------------------------------------------------
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # -----------------------------------------------------
    # Applications du projet
    # -----------------------------------------------------
    'accounts',
    'entreprises',
    'stages',
    'candidatures',
    'encadrement',
    'journal',
    'rapports',
    'evaluations',
    'dashboard',
    'notifications',
    'demandes',
    'statistiques',

    # -----------------------------------------------------
    # API REST & Outils de Production
    # -----------------------------------------------------
    'rest_framework',
    'corsheaders',
]


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [
    # CORS (Doit impérativement rester en haut)
    'corsheaders.middleware.CorsMiddleware',

    # Sécurité Django
    'django.middleware.security.SecurityMiddleware',

    # Gestion des fichiers statiques WhiteNoise
    'whitenoise.middleware.WhiteNoiseMiddleware',

    # Sessions
    'django.contrib.sessions.middleware.SessionMiddleware',

    # Requêtes communes
    'django.middleware.common.CommonMiddleware',

    # Protection CSRF
    'django.middleware.csrf.CsrfViewMiddleware',

    # Authentification
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # Messages
    'django.contrib.messages.middleware.MessageMiddleware',

    # Protection iframe
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =========================================================
# URL CONFIGURATION
# =========================================================

ROOT_URLCONF = 'config.urls'


# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# =========================================================
# WSGI
# =========================================================

WSGI_APPLICATION = 'config.wsgi.application'


# =========================================================
# BASE DE DONNÉES POSTGRESQL (LOCAL & SUPABASE/RENDER)
# =========================================================

DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # Mode Production (Render + Supabase IPv4 Pooler)
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=True
        )
    }
else:
    # Mode Local (PostgreSQL PC)
    DATABASES = {
        'default': dj_database_url.parse(
            'postgresql://postgres:mon%20mdb%20@localhost:5432/gestion_stage',
            conn_max_age=600,
            ssl_require=False
        )
    }


# =========================================================
# VALIDATION DES MOTS DE PASSE
# =========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =========================================================
# LANGUE ET TEMPS
# =========================================================

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Indian/Antananarivo'

USE_I18N = True

USE_TZ = True


# =========================================================
# CORS — REACT
# =========================================================

CORS_ALLOW_ALL_ORIGINS = True


# =========================================================
# FICHIERS STATIQUES (PRODUCTION)
# =========================================================

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise tolérant (évite les erreurs 500/404 si un fichier manque au manifeste)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}


# =========================================================
# FICHIERS MEDIA
# =========================================================

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'


# =========================================================
# UTILISATEUR PERSONNALISÉ
# =========================================================

AUTH_USER_MODEL = 'accounts.User'


# =========================================================
# REST FRAMEWORK
# =========================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}


# =========================================================
# SIMPLE JWT
# =========================================================

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}


# =========================================================
# TYPE D'IDENTIFIANT AUTOMATIQUE
# =========================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'