"""
Django settings for config project.

Generated by 'django-admin startproject'
"""

from pathlib import Path
from datetime import timedelta


# =========================================================
# CHEMIN PRINCIPAL DU PROJET
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# =========================================================
# SECURITY
# =========================================================

SECRET_KEY = 'django-insecure-d@tv+y*y0a3&cuzw--r-2v(knnrwwqf5jww#p1$wkn_sry5j91'

DEBUG = True

ALLOWED_HOSTS = []


# =========================================================
# APPLICATIONS INSTALLÉES
# =========================================================

INSTALLED_APPS = [

    # -----------------------------------------------------
    # Applications Django
    # -----------------------------------------------------

    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',


    # -----------------------------------------------------
    # Applications du projet
    # -----------------------------------------------------

    'accounts',

    'entreprises',

    'stages',

    'candidatures',

    'encadrement',

    'journal',

    'rapports',

    'evaluations',

    'dashboard',

    'notifications',

    'demandes',

    'statistiques',


    # -----------------------------------------------------
    # API REST
    # -----------------------------------------------------

    'rest_framework',

    'corsheaders',

]


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [

    # CORS
    'corsheaders.middleware.CorsMiddleware',

    # Sécurité
    'django.middleware.security.SecurityMiddleware',

    # Sessions
    'django.contrib.sessions.middleware.SessionMiddleware',

    # Requêtes communes
    'django.middleware.common.CommonMiddleware',

    # Protection CSRF
    'django.middleware.csrf.CsrfViewMiddleware',

    # Authentification
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # Messages
    'django.contrib.messages.middleware.MessageMiddleware',

    # Protection iframe
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]


# =========================================================
# URL CONFIGURATION
# =========================================================

ROOT_URLCONF = 'config.urls'


# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [

    {

        'BACKEND':
            'django.template.backends.django.DjangoTemplates',


        # -------------------------------------------------
        # IMPORTANT
        # Permet à Django de trouver :
        #
        # templates/admin/login.html
        # templates/admin/base_site.html
        # templates/admin/logged_out.html
        # -------------------------------------------------

        'DIRS': [

            BASE_DIR / 'templates',

        ],


        # Chercher également dans templates des applications

        'APP_DIRS': True,


        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]


# =========================================================
# WSGI
# =========================================================

WSGI_APPLICATION = 'config.wsgi.application'


# =========================================================
# BASE DE DONNÉES POSTGRESQL
# =========================================================

DATABASES = {

    'default': {

        'ENGINE':
            'django.db.backends.postgresql',

        'NAME':
            'gestion_stage',

        'USER':
            'postgres',

        'PASSWORD':
            'azerty',

        'HOST':
            'localhost',

        'PORT':
            '5432',

    }

}


# =========================================================
# VALIDATION DES MOTS DE PASSE
# =========================================================

AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME':
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME':
            'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]


# =========================================================
# LANGUE ET TEMPS
# =========================================================

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Indian/Antananarivo'

USE_I18N = True

USE_TZ = True


# =========================================================
# CORS — REACT
# =========================================================

CORS_ALLOW_ALL_ORIGINS = True


# =========================================================
# FICHIERS STATIQUES
# =========================================================

STATIC_URL = '/static/'


# ---------------------------------------------------------
# Dossier static personnalisé
#
# Exemple :
#
# static/
# └── admin/
#     └── css/
#         ├── custom_admin.css
#         └── custom_login.css
# ---------------------------------------------------------

STATICFILES_DIRS = [

    BASE_DIR / 'static',

]


# =========================================================
# FICHIERS MEDIA
# =========================================================

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'


# =========================================================
# UTILISATEUR PERSONNALISÉ
# =========================================================

AUTH_USER_MODEL = 'accounts.User'


# =========================================================
# REST FRAMEWORK
# =========================================================

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (

        'rest_framework_simplejwt.authentication.JWTAuthentication',

    ),

}


# =========================================================
# SIMPLE JWT
# =========================================================

SIMPLE_JWT = {

    'ACCESS_TOKEN_LIFETIME':
        timedelta(hours=1),

    'REFRESH_TOKEN_LIFETIME':
        timedelta(days=7),

    'ROTATE_REFRESH_TOKENS':
        False,

    'BLACKLIST_AFTER_ROTATION':
        False,

}


# =========================================================
# TYPE D'IDENTIFIANT AUTOMATIQUE
# =========================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'