# Generated by Django 5.2.17 on 2026-08-07 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('domaine', models.CharField(max_length=100)),
                ('competences_requises', models.TextField()),
                ('duree', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombre_places', models.IntegerField(default=1)),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('FERME', 'Fermé')], default='OUVERT', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres_stage', to='entreprises.entreprise')),
            ],
        ),
    ]
