# Generated by Django 5.2.17 on 2026-08-20 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
        ('entreprises', '0001_initial'),
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='demandes/cv/'),
        ),
        migrations.AddField(
            model_name='demande',
            name='lettre_motivation_fichier',
            field=models.FileField(blank=True, null=True, upload_to='demandes/lettres/'),
        ),
        migrations.AddField(
            model_name='demande',
            name='lettre_motivation_texte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='entreprises.entreprise'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='stages.offrestage'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='type_demande',
            field=models.CharField(choices=[('STAGE', 'Demande de stage'), ('CONVENTION', 'Convention de stage'), ('AUTRE', 'Autre demande')], default='STAGE', max_length=20),
        ),
    ]
