# Generated by Django 5.2.17 on 2026-08-22 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0001_initial'),
        ('demandes', '0002_demande_cv_demande_lettre_motivation_fichier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaturestage',
            name='demande',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidature', to='demandes.demande'),
        ),
        migrations.AddField(
            model_name='candidaturestage',
            name='lettre_motivation_fichier',
            field=models.FileField(blank=True, null=True, upload_to='candidatures/lettres/'),
        ),
        migrations.AlterField(
            model_name='candidaturestage',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='candidatures/cv/'),
        ),
        migrations.AlterField(
            model_name='candidaturestage',
            name='lettre_motivation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
